### ISSUE TITLE
Android Basics: dice-roller-images

### ISSUE THREAD

**Issue by wal0x** [google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution#6]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-dice-roller-images?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-dice-roller-images#4

**In which task and step of the codelab can this issue be found?**

5

**Describe the problem**

When I click on button Roll many times and fast the application crashes

**Steps to reproduce?**
1. Open App Dice roller
2. Click on Roll super fast and many times
3. Application crashes

2020-12-11 19:07:15.262 5970-5970/com.example.diceroller E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.diceroller, PID: 5970
    java.lang.OutOfMemoryError: Failed to allocate a 102700812 byte allocation with 16777216 free bytes and 53MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1179)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
        at android.content.res.Resources.getDrawable(Resources.java:1640)
        at android.content.Context.getDrawable(Context.java:525)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
        at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)
        at com.example.diceroller.MainActivity.rollDice(MainActivity.kt:68)
        at com.example.diceroller.MainActivity.access$rollDice(MainActivity.kt:27)
        at com.example.diceroller.MainActivity$onCreate$1.onClick(MainActivity.kt:40)
        at android.view.View.performClick(View.java:6213)
        at android.widget.TextView.performClick(TextView.java:11074)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:992)
        at android.view.View$PerformClick.run(View.java:23645)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Versions**
_Android Studio version:_ 4.1
_API version of the emulator:_ Android 7.0

**Additional information**
Is in releation with the fact that the dice image take time before changing after clicking on the Roll button ?

**Comment by amindadgar** [comment]
due to this link you can find your answer
https://stackoverflow.com/a/32245018

**Further instruction:** garbage collector in Kotlin and java language is automatic, When you initial a variable in this languages after you finished your job with variable the garbage collector will free the variable space from heap memory automatically ( in C++ language you have to do this on your own ).
The problem here is when you click the roll button very fast the heap memory will become full and the memory cannot allocate more memory ( and garbage collector cannot free the space ).

**Comment by jhansitavva** [comment]
@wal0x 
Thank you for reaching out to us.
We have uploaded smaller images for dice roller. [Please download it again from here and try](https://github.com/google-developer-training/android-basics-kotlin-dice-roller-with-images-app-solution/raw/master/dice_images.zip).
Kindly update the issue if you still face the problem.
